### ISSUE TITLE
function hf.match_otu_qual does not exist

### ISSUE THREAD

**Issue by pat-rig** [MaudeDavidLab/gut_microbiome_embeddings#1]
In `match_otu_mapping.py` line 24, you call `hf.match_otu_qual(otu, qual_vecs)`, however no such function is defined in `helper_functions.py`.

I am not sure if I know exactly what this line is supposed to do so it's hard for me to fix.
(I think it is supposed to remove ASVs from the sample by asv matrix which are not present in the transformation matrix?)
I've found a function `matchOtuQual` in `helper_functions.py`, which returns only one object.
However, in the aforementioned line  two objects are expected to be returned.
Even though the object `qual_vecs_clean` is not used anymore throughout the script. 

Also the object `qual_vecs` does not exist, but I guess it's only one line to be added:
`qual_vecs = getQualVecs('some_directory')`
is that correct?

I am trying to reproduce your results and assess the uncertainty of the embedding afterwards.
I'd appreciate any help very much, since I can't continue working on the project without this postprocessing step.

**Comment by kiti15237** [comment]
Hi,

Thank you for your interest and for catching this mistake! You can feel
free to delete the match_otu_qual function call in line 24 of
match_otu_mapping.py, it's a mistake that it's in there. Instead, this
script is supposed to match up the sample ids between the mapping file and
the otu table (there was some inconsistency in the downloading process
between the two). We'll call the function you mentioned, matchOtuQual, in
the scripts predict_AGP_testset.py and train_ag_test_half/huttenhower.py.
You shouldn't have to call the getQualVecs(directory) function until then.
When it comes time to call it, you'll pass it the file path to the data
directory. Effectively, it will be looking for the
filepath data/embed/embed_.07_100dim.txt (you can change that 100dim to be
50dim, 250dim, 500dim, or 750dim in helper_functions so long as you
download the appropriate data file from here first:
http://files.cgrb.oregonstate.edu/David_Lab/microbiome_embeddings/data/embed/
).

I fixed a couple of small bugs in the process of making sure I gave correct
answers just now, so it might be worth it to re-pull from github
(specifically I changed getQualVecs so that you may pass the dimension as a
parameter and fixed a little bug in match_otu_map() in helper_functions.py.

Hope this is helpful, please let me know if you run into more problems. I'm
very happy for the help catching inconsistencies!
Christine

**Comment by pat-rig** [comment]
Thank You for the fast reply.
The script works fine now :)

Patrick
